server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: job-auth-service
          uri: lb://job-auth-service
          predicates:
            - Path=/api/auth/**
        - id: user-profile-service
          uri: lb://user-profile-service
          predicates:
            - Path=/api/users/**
        - id: job-service
          uri: lb://job-service
          predicates:
            - Path=/api/jobs/**
        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/api/applications/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

